apiVersion: v1
kind: Service
metadata:
  name: hack-service
spec:
  type: ClusterIP
  selector:
    app: hack
  ports:
    - protocol: TCP
      port: 8000  # Cluster port
      targetPort: 80 # Container port
